### ISSUE TITLE
Does not work with vscode-languageserver-node

### ISSUE THREAD

**Issue by phil294** [AndCake/micro-plugin-lsp#1]
LSP servers written with [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) (library for node) don't seem to work wiht this micro client plugin. For example the official example server: https://github.com/microsoft/vscode-extension-samples/blob/main/lsp-sample/server/src/server.ts
`onInitialized` seems to never be called. Though I looked into it, I have no idea why 😕 Also tried [Vetur](https://github.com/vuejs/vetur/) / [fork](https://github.com/phil294/coffeesense/)

I realize this is only a demo client implementation, just thought you might wanna know. Thanks for doing this, it's awesome! If this worked and also did autocompletion (no idea how complex that is), this could indeed solve the entire [issue](https://github.com/zyedidia/micro/issues/1138) of LSP in micro.

**Comment by AndCake** [comment]
Can you provide a little more info on how you configured this LSP server in your micro settings.json?

**Comment by phil294** [comment]
Sure :)

```bash
cd /tmp
git clone --depth=1 https://github.com/microsoft/vscode-extension-samples/
cd vscode-extension-samples/lsp-sample/server/
npm i
npm i typescript
# Confirm no error when running server:
node src/server.js --stdio

git clone --depth=1 https://github.com/AndCake/micro-plugin-lsp ~/.config/micro/plug/lsp

### Edit ~/.config.micro/settings.json:
### Set
### "lsp.server": "typescript=node /tmp/vscode-extension-samples/lsp-sample/server/src/server.js --stdio",

echo 'FAIL' > ts.ts
micro -debug ts.ts
```
...and no error is shown (`FAIL` should have an error because this extension fails for all all-capslock words of >= 2 chars length).

`log.txt`:
```
2022/03/18 14:46:54 Micro started
2022/03/18 14:46:54 ONBUFFEROPEN unknown
2022/03/18 14:46:54 ONBUFFEROPEN unknown
2022/03/18 14:46:54 Starting server typescript
2022/03/18 14:46:54 send typescript sending initialize
2022/03/18 14:46:54 send typescript queueing initialized
2022/03/18 14:46:54 ONBUFFEROPEN typescript
2022/03/18 14:46:54 Found running lsp server for  typescript firing textDocument/didOpen...
2022/03/18 14:46:54 send typescript queueing textDocument/didOpen
```

**Comment by AndCake** [comment]
Perfect, thanks! I am able to reproduce the issue now. It seems the lsp-sample server is not actually responding to the initialize message. So far I have been unable to get any kind of response by sending messages to that server's STDIN. I used the node JS inspect command to analyze where it goes wrong and it seems messages sent to STDIN are just never even received by the LSP server. I'll look into this a little more.

**Comment by AndCake** [comment]
I created PR https://github.com/AndCake/micro-plugin-lsp/pull/2 - can you checkout the branch bug/1-does-not-work-with-vscode and confirm if this is functional on your side? With the fix it seems to work on my side and doesn't seem to have any negative impact on the other tested LSPs. If this works for you, I would bring it to master.

**Comment by phil294** [comment]
okay, nice catch - `\r\n`, what a strange requirement... the server initializes now, but diagnostics are not shown. I guess you didn't see them either? The log now says things like
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Unhandled method initialized"}}
{"jsonrpc":"2.0","id":2,"error":{"code":-32601,"message":"Unhandled method textDocument/didOpen"}}
```
so something is probably still not right.

I wanted to debug this too to spare you the work, but can't get the inspector to work. How did you do that? `"lsp.server": "typescript=node /.../server.js --inspect` and then open `chrome://inspect`?

**Comment by AndCake** [comment]
I used the following settings for debugging: 

```
"lsp.server": "typescript=node --inspect-brk /tmp/vscode-extension-samples/lsp-sample/server/out/server.js --stdio"
```

Completions seem to work, though (press Ctrl+Space). I investigated and it seems that in `vscode-jsonrpc/lib/common/connection.js:371` the registered request handlers from the `lsp-sample/server` do indeed not contain the message handlers for `initialized` nor for `textDocument/didOpen`. I see the following handlers having been registered by the `lsp-sample/server` with the vscode-jsonrpc connection:

```
{
    "initialize": {
        "type": {
            "method": "initialize",
            "numberOfParams": 1,
            "_parameterStructures": {
                "kind": "byName"
            }
        }
    },
    "shutdown": {
        "type": {
            "method": "shutdown",
            "numberOfParams": 0
        }
    },
    "textDocument/completion": {
        "type": {
            "method": "textDocument/completion",
            "numberOfParams": 1,
            "_parameterStructures": {
                "kind": "byName"
            }
        }
    },
    "completionItem/resolve": {
        "type": {
            "method": "completionItem/resolve",
            "numberOfParams": 1,
            "_parameterStructures": {
                "kind": "byName"
            }
        }
    },
    "textDocument/willSaveWaitUntil": {
        "type": {
            "method": "textDocument/willSaveWaitUntil",
            "numberOfParams": 1,
            "_parameterStructures": {
                "kind": "byName"
            }
        }
    }
}
```

I am unsure why the initialized and didOpen might be missing from this. I tried with sleeping between requests to make sure we have enough time to register it, but so far to no avail.

**Comment by AndCake** [comment]
I think I figured it out: apparently the big difference between notifications and requests in an LSP is the absence of an ID property (as I found reading the spec in more detail). The changes are implemented in the above PR and seem to be working fine for me now including the diagnostics. Let me know if it is working on your side too. Thanks for your help with this so far!

**Comment by phil294** [comment]
Seems to be broken again ;(

Autocompletions are there, but errors aren't shown. Same with Deno. With gopls, everything is fine.

Debugging the node server revealed that `validateTextDocument` indeed collects errors and probably sends them but they seem to get lost somewhere along the way

**Comment by phil294** [comment]
If I add

```js
documents.onDidChangeContent(async change => {
    const diagnostics = await validateTextDocument(change.document);
    // vvvvvv added this line vvvvvv
    connection.sendDiagnostics({ uri: change.document.uri, diagnostics });
});
```
to the extension sample, it works. Apparently the wiring is wrong somewhere?

**Comment by phil294** [comment]
Ah here we go, this line was already there once upon a time:

https://github.com/microsoft/vscode-extension-samples/commit/48f100fab89e8dd005b881ecea1057f0ffacf263#diff-1d9e3f731e806171e44f99395224c664e78cf42edec01303f9dca7d328f05427L181 (very bottom)

Is it possible that micro-plugin-lsp needs to support "pull diagnostics"? And why wasn't this implemented in a backward-compatible way by Microsoft? oof >.<
