### ISSUE TITLE
Looking for Cargo.toml in a python project

### ISSUE THREAD

**Issue by rochacbruno** [AndCake/micro-plugin-lsp#11]
HI, thanks for this amazing project

I tried following the instructions on the readme and opened a Python file.

message on status bar:

```
could not find  `Cargo.toml` in `path` or any parent directory
```

It also asked me to add `rls` to my rustup toolchain, so looks like this is not considering the filetype.

**Comment by AndCake** [comment]
Hi! I updated the messaging for this. Since we now have default values for the LSP configuration, it is unnecessary to show such messages in the status bar. It is now only logged.
