### ISSUE TITLE
Auto completion is duplicating the already typed parts of string

### ISSUE THREAD

**Issue by rochacbruno** [AndCake/micro-plugin-lsp#12]
I am using https://github.com/python-lsp/python-lsp-server installed with `[all]` option.

When I go to a Rune such as `os.pa` and hit `Ctrl+Space` I expected the autocomplete to give me `os.pa[th]` but is is giving me `os.pa[path]`

Is there any config I need to add?

![Screenshot_2022-04-08_09-22-25](https://user-images.githubusercontent.com/458654/162396065-968b9e3c-5456-4202-a536-bb594a764fc6.png)

Thanks again

**Comment by rochacbruno** [comment]
same on rls


![Screenshot_2022-04-08_11-04-41](https://user-images.githubusercontent.com/458654/162414319-baf04047-6055-43c5-8581-9ee968de2c6b.png)

**Comment by AndCake** [comment]
@rochacbruno I created a fix for the issue above. Can you check if this works for you?

**Comment by rochacbruno** [comment]
@AndCake yes it works great! thanks again
