### ISSUE TITLE
Feature Request: Linux/Bash Style Tab Completion

### ISSUE THREAD

**Issue by terokarvinen** [AndCake/micro-plugin-lsp#16]
**Tab completes unambiguous part. Double tab lists possible completions.** 

## Rationale

Tab completion can be both faster and more helpful when done similar to Jupyter iPython, Bash, and many other popular Linux shells. 

There are two main uses for auto completion

- Faster typing of familiar but long words (xyz.FoobarFactoryFactoryHelper)
- Introspection, what members does this thing have in this library or class (math.)

Completion can be faster when Tab works Linux/Bash/iPython style. A simple UI for additional information can be shown when needed. 

## How Bash Style Autocomplete Works

When user presses Tab, complete current word as far as possible. User chooses completion by typing the next character. 

Alternatively, user can press tab twice more (in the middle of completion) to see possible options. Alternatives could be shown on the half screen buffer. 

## Example: Faster Typing of Long Names

For example, consider a case with possible completions:

	foo.SystemReadWriteFactory
	foo.SystemReadWriteHandle
	foo.WipeHelper
	foo.bar
	foo.foo

User types

	foo.S[Tab]

System autocompletes

	foo.SystemReadWrite

User types additional "F". System autocompletes the only option that's left:

	foo.SystemReadWriteFactory 

## Example: Show Possible Completions

For example, user wants to know what's available in an imaginary "random" library

	random.[tab][tab][tab]

A half screen buffer below opens. It shows all available options at the same time. This way, user can glance what's available without cycling trough options one at the time.

User chooses the next option by typing more characters and pressing tab. Focus is always kept on the main code.

After the completion, the half-screen buffer closes automatically. Alternatively, user can close the half-screen buffer by pressing ESC or using arrow keys to move away from completion. 

Optionally / in the future, the half screen buffer could show 

- Function signatures for completions
- Highlight the next character which user can type to choose this completion

As pressing tab three times in the middle of completion is not a common sequence of keys typed, it's likely that the half-screen (possible completions) window only shows when user wants it. 

## Existing LSP Plugin and Micro Features and Conventions

Tab: By default, micro tab is bound to "Autocomplete|IndentSelection|InsertTab". So tab is already used for naive autocomplete. This could be changed to "LspComplete|IndentSelection|InsertTab". Alternatively, user could have a separate key for autocompletion. 

Half-screen: Show options in half-screen buffer is already used in LSP plugin's show references Alt-R.

Linux / Bash / iPython style autocomplete: Already used in popular Linux shells and familiar to Linux users. 

Complete, then show options: The leading alternative Python shell Jupyter uses this in iPython3. The most popular Linux shell Bash uses this style. 

### Benefits

- Typing familiar names is much faster. It does not depend on iteratively cycling different options (cycle-read-cycle-read-cycle-whoops-previous-read-accept). 
- It allows using a single key to both complete and accept completion
- Introspection, seeing what's available next, can show multiple available options at the same time. 
- In the future, there is space to show much more information for alternatives. 
- Familiar to Linux users, probably a major user group for a TUI editor like Micro

**Comment by phil294** [comment]
If I understand you correctly, the half screen buffer would only open with 3xtab. I personally would prefer this to be the default, perhaps accessible by another hotkey. But that is only a minor note. Also, the half screen window should probably have a reasonable max height.

> Autocomplete|IndentSelection|InsertTab". So tab is already used for naive autocomplete. This could be changed to "LspComplete|IndentSelection|InsertTab".

More like to `"LspComplete|Autocomplete|IndentSelection|InsertTab"`, in case there is no LSP active, no? But it's user-configurable anyway

That being said, I think this is a great suggestion!

**Comment by terokarvinen** [comment]
Thanks for the comments!

Yes, the half screen suggestion window would only open if user presses triple tab in the middle of completion. Otherwise, there is nothing to show. As the completion is done or user moves, again, there are no completions to show. I also like features that are easily reachable, but out of your face when you don't need them. 

I also consider this discoverable. Many users of tab completion keep hitting tab when they don't know what to type next, and find out about this feature in Bash that way. 

Naive autocomplete is a little too eager to help, and false positive rate is too high for my taste. So I would prefer to receive only correct suggestions. Bash style completion (unambiguous part only) achieves this in some existing systems, such as bash. But, as you say, it's a user preference.

**Comment by AndCake** [comment]
This feature would be very neat indeed. I have experimented with this a little already, but it seems that there is a limitation in how micro handles plugin's callback return values. This leads to the apparent inability to give/not give it to the next entry in the tab binding configuration. Essentially that means, that the plugin needs to completely re-implement all logic for indenting  the current line as well as a selection of lines from scratch. 

I will try to fiddle around with this some more and see if the recent changes I did for the autocomplete are actually edging us closer to being able getting the indentation sorted.

**Comment by terokarvinen** [comment]
Happy to hear about the advancement and your tests.  

If it really ends up being a current limitation of micro, I wonder if @zyedidia would be interested in improving that. I indeed thought that you just "return false" or similar, and the next one takes over. 

A possible intermediate solution could be implementing it to alt-J with no fallbacks. This way, there will never be a false positive; and just the tab support in micro is left to implement. And one day, this could be in Tab.

**Comment by terokarvinen** [comment]
@AndCake , another idea to get fallback working. Considering keybinding "LspComplete|IndentSelection|InsertTab", you mentioned that plugin can't easily give control to next action. E.g. if LspComplete is not possible, it should advance to IndentSelection. 

If advancement is not possible, the plugin could internally try the other actions. After all, they are commands and probably callable from a plugin. E.g. "LspComplete-IndentSelection-InsertTab". If there is no completion, the plugin could automatically call IndentSelection command. 

I would expect that most users are using the default setting, and some minority (including myself) have disabled the naive autocomplete.

**Comment by AndCake** [comment]
As a first throw at it, I implemented the indentation logic, so you can now rebind the autocompletion to tab. However, the partial application of autocompletions I am still working on. Let's see when I get this in a state where I feel it is functional.

**Comment by terokarvinen** [comment]
Thanks, @AndCake!

**Comment by terokarvinen** [comment]
Just tried it. You're advancing fast! 

Great first experience: OK, works initially with Go fmt... Which package should I try next, trying to remember Go after some other language... And before thinking about it, I had tab tabbed my way to list of packages, and selected one! 

Some ideas for improvement

- The bottom buffer should only open on double tab, not automatically
- The word to be completed should be deselected, and cursor placed at the end. This way, user can keep typing. 
- I currently sometimes get a mix of bash style tab completion and the previous cycle-read-cycle-whoops-read-accept completion. 
- Function descriptions are useful when I'm thinking what to use. Many more one-line signatures would fit, using a style similar to alt-K: "func fmt.Println(a ...interface{}) (n int, err error)Println formats using the default formats for its operands and". Autocomplete buffer at the bottom would list function signatures as one liners for choice, then user could pick one and use alt-D jump to description to read the details. 
- Once I add more imports to Go file, autocomplete shows a bug: fmt.P[tab] offers libraries as completions: "bufio", "bytes"...

You've just shown that indeed it's possible to do Linux style Tab completion in Micro. And the interface ideas seem to work. And you even got the function signatures there. 

Good work, @AndCake!

**Comment by raidenXR** [comment]
the plugin works with Zig language server. 
hover, definition lookup, formatting, looking up references, those work fine.
_Ctrl-space for completion_ though throws the error below

>Lua API error: main:475: attempt to index a non-table object(nil) with key 'start'
stack traceback:
	main:475: in function 'response'
	main:295: in main chunk
	[G]: ?

completion with pyhon works though

**Comment by raidenXR** [comment]
so I guess you could add Zig at _Testing_ section of README.md

**Comment by AndCake** [comment]
@raidenXR thanks for testing zig! I will move your feedback into a new ticket though, so that it can be worked on independently of this issue here.
