### ISSUE TITLE
Trying to get Eclipse JDT-LS to work

### ISSUE THREAD

**Issue by szabodanika** [AndCake/micro-plugin-lsp#22]
I installed [JDT-LS 1.9.0 ](https://github.com/eclipse/eclipse.jdt.ls)using a [Brew formula](https://github.com/szabodanika/homebrew), then added it to settings.json like so: 
```
"lsp.server": "java=jdt-ls,python=pyls,go=gopls,typescript=deno lsp
       │ ={\"importMap\": \"./import_map.json\"}",
```

On launching Micro, I get 
```
Lua API error: main:291: attempt to index a non-table object(nil) with key 'capabilities'
stack traceback:
	main:291: in main chunk
	[G]: ?
```

At a quick glance, this is probably related to line 292 in main.lua:
```
capabilities[filetype] = data.result.capabilities or {}
```

Could this be an issue with the language server or the plugin?

**Comment by szabodanika** [comment]
**Update**

I changed line 292 from 
`capabilities[filetype] = data.result.capabilities or {}`
to
`capabilities[filetype] = {}`

and JDT-LS seems to work now more or less, it did not crash and I see some messages from the language server.

I'm sure this change breaks some other things but at least it confirms the source of the error and it can be a temporary workaround for those facing the same error.

**Comment by AndCake** [comment]
Hi @szabodanika , can you provide some more details from the log (i.e. run micro with the `-debug` parameter and then pasting the log.txt file here (or at least the relevant excerpt before the error happens)?

**Comment by szabodanika** [comment]
Here's my entire log.txt after starting micro with an empty buffer (`micro -debug`) and leaving line 292 unchanged: 

<details>

2022/04/17 18:28:13 Micro started
2022/04/17 18:28:13 ONBUFFEROPEN unknown
2022/04/17 18:28:13 ONBUFFEROPEN unknown
2022/04/17 18:28:13 ONBUFFEROPEN unknown
2022/04/17 18:28:13 Starting server java
2022/04/17 18:28:13 send java sending initialize Content-Length: 535
{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 23811, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 18:28:13 send java queueing initialized
2022/04/17 18:28:13 Starting server python
2022/04/17 18:28:13 send python sending initialize Content-Length: 535
{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 23811, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 18:28:13 send python queueing initialized
2022/04/17 18:28:13 Starting server go
2022/04/17 18:28:13 send go sending initialize Content-Length: 535
{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 23811, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 18:28:13 send go queueing initialized
2022/04/17 18:28:13 Starting server typescript
2022/04/17 18:28:13 send typescript sending initialize Content-Length: 567
{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 23811, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {"importMap": "./import_map.json"}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 18:28:13 send typescript queueing initialized
2022/04/17 18:28:13 ONBUFFEROPEN filemanager
2022/04/17 18:28:13 ONEXIT python 
2022/04/17 18:28:13 ONEXIT go 
2022/04/17 18:28:13 ONSTDERR Starting Deno language server...
  version: 1.20.6 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno
2022/04/17 18:28:13 ONSTDERR OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
2022/04/17 18:28:13 ONSTDERR Setting import map from workspace settings: "./import_map.json"
  Resolved import map: "/Users/daniel/import_map.json"
2022/04/17 18:28:13 send typescript sending Content-Length: 57
{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 18:28:13 ONSTDERR Server ready.
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Main thread is waiting
2022/04/17 18:28:14 send java sending Content-Length: 57
{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 u003eu003e initialize
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Initializing Java Language Server 1.9.0.202203031534
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Static Commands: []
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.upgradeGradle, java.project.resolveSourceAttachment, java.project.addToSourcePath]
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Starting org.eclipse.m2e.core
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Started org.eclipse.m2e.core 1ms
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 ProjectRegistryRefreshJob finished 13ms
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Starting org.eclipse.buildship.core
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 Started org.eclipse.buildship.core 6ms
2022/04/17 18:28:14 2022. ápr. 17. 18:28:14 LoadingGradleVersionJob finished 13ms

</details>

**Comment by AndCake** [comment]
Could you do the same with the fix in place? Because in the log above I can't see anything being received by the plugin from the JDT LS except for an "error" message (messages through stderr)

**Comment by szabodanika** [comment]
I tested the plugin again in three cases, here are the log files. For some reason running micro as sudo works without touching line 292. I hope you find this helpful, I am quite confused myself now

Leaving line 292 as original, non sudo (throws error)
<details>
2022/04/17 19:16:51 Micro started
2022/04/17 19:16:51 ONBUFFEROPEN unknown
2022/04/17 19:16:51 ONBUFFEROPEN unknown
2022/04/17 19:16:51 ONBUFFEROPEN unknown
2022/04/17 19:16:51 Starting server java
2022/04/17 19:16:51 send java sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26073, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:16:51 send java queueing initialized
2022/04/17 19:16:51 Starting server python
2022/04/17 19:16:51 send python sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26073, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:16:51 send python queueing initialized
2022/04/17 19:16:51 Starting server go
2022/04/17 19:16:51 send go sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26073, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:16:51 send go queueing initialized
2022/04/17 19:16:51 Starting server typescript
2022/04/17 19:16:51 send typescript sending initialize Content-Length: 567

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26073, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {"importMap": "./import_map.json"}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:16:51 send typescript queueing initialized
2022/04/17 19:16:51 ONBUFFEROPEN filemanager
2022/04/17 19:16:51 ONEXIT python 
2022/04/17 19:16:51 ONEXIT go 
2022/04/17 19:16:51 ONSTDERR Starting Deno language server...
  version: 1.20.6 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno

2022/04/17 19:16:51 ONSTDERR OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

2022/04/17 19:16:51 ONSTDERR Setting import map from workspace settings: "./import_map.json"
  Resolved import map: "/Users/daniel/import_map.json"

2022/04/17 19:16:51 send typescript sending Content-Length: 57

{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 19:16:51 ONSTDERR Server ready.

2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Main thread is waiting
2022/04/17 19:16:51 send java sending Content-Length: 57

{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 u003eu003e initialize
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Initializing Java Language Server 1.9.0.202203031534
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Static Commands: []
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.upgradeGradle, java.project.resolveSourceAttachment, java.project.addToSourcePath]
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Starting org.eclipse.m2e.core
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Started org.eclipse.m2e.core 1ms
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 ProjectRegistryRefreshJob finished 13ms
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Starting org.eclipse.buildship.core
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 Started org.eclipse.buildship.core 8ms
2022/04/17 19:16:51 2022. ápr. 17. 19:16:51 LoadingGradleVersionJob finished 13ms

</details>

Changing line 292 as shown above, non sudo (does not throw error)
<details>
2022/04/17 19:15:16 Micro started
2022/04/17 19:15:16 ONBUFFEROPEN unknown
2022/04/17 19:15:16 ONBUFFEROPEN unknown
2022/04/17 19:15:16 ONBUFFEROPEN unknown
2022/04/17 19:15:16 Starting server java
2022/04/17 19:15:16 send java sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26000, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:15:16 send java queueing initialized
2022/04/17 19:15:16 Starting server python
2022/04/17 19:15:16 send python sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26000, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:15:16 send python queueing initialized
2022/04/17 19:15:16 Starting server go
2022/04/17 19:15:16 send go sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26000, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:15:16 send go queueing initialized
2022/04/17 19:15:16 Starting server typescript
2022/04/17 19:15:16 send typescript sending initialize Content-Length: 567

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26000, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {"importMap": "./import_map.json"}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:15:16 send typescript queueing initialized
2022/04/17 19:15:16 ONBUFFEROPEN filemanager
2022/04/17 19:15:16 ONEXIT go 
2022/04/17 19:15:16 ONEXIT python 
2022/04/17 19:15:16 ONSTDERR Starting Deno language server...
  version: 1.20.6 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno

2022/04/17 19:15:16 ONSTDERR OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

2022/04/17 19:15:16 ONSTDERR Setting import map from workspace settings: "./import_map.json"
  Resolved import map: "/Users/daniel/import_map.json"

2022/04/17 19:15:16 send typescript sending Content-Length: 57

{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 19:15:16 ONSTDERR Server ready.

2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Main thread is waiting
2022/04/17 19:15:17 send java sending Content-Length: 57

{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e initialize
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Initializing Java Language Server 1.9.0.202203031534
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Static Commands: []
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.upgradeGradle, java.project.resolveSourceAttachment, java.project.addToSourcePath]
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Wait for AutoBuildOffJob start
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Wait for AutoBuildOffJob end 0ms
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Starting org.eclipse.m2e.core
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Started org.eclipse.m2e.core 1ms
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 ProjectRegistryRefreshJob finished 0ms
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Starting org.eclipse.buildship.core
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Started org.eclipse.buildship.core 8ms
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 LoadingGradleVersionJob finished 13ms
2022/04/17 19:15:17 Unhandled message 1 java Content-Length: 118

{"jsonrpc":"2.0","method":"language/status","params":{"type":"Starting","message":"0% Starting Java Language Server"}}
2022/04/17 19:15:17 Unhandled message 1 java Content-Length: 2095

{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{"includeText":true}},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","@","#","*"," "]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":true,"codeLensProvider":{"resolveProvider":true},"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":";","moreTriggerCharacter":["\n","}"]},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["java.edit.organizeImports","java.project.refreshDiagnostics","java.project.import","java.navigate.openTypeHierarchy","java.project.removeFromSourcePath","java.project.listSourcePaths","java.project.resolveStackTraceLocation","java.project.getAll","java.project.isTestFile","java.project.getClasspaths","java.navigate.resolveTypeHierarchy","java.edit.stringFormatting","java.project.getSettings","java.project.updateSourceAttachment","java.project.upgradeGradle","java.project.resolveSourceAttachment","java.project.addToSourcePath"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"callHierarchyProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"legend":{"tokenTypes":["namespace","class","interface","enum","enumMember","type","typeParameter","method","property","variable","parameter","modifier","keyword","annotation","annotationMember","record","recordComponent"],"tokenModifiers":["abstract","static","readonly","deprecated","declaration","documentation","public","private","protected","native","generic","typeArgument","importDeclaration","constructor"]},"range":false,"full":{"delta":false},"documentSelector":[{"language":"java","scheme":"file"},{"language":"java","scheme":"jdt"}]}}}}
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Creating the Java project jdt.ls-java-project
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e initialized
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Default VM Install changed from  null to net.java.openjdk.jdk-/Users/daniel/Library/Java/JavaVirtualMachines/openjdk-17.0.2/Contents/Home
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 defaultVMInstallChanged -u003e force update of jdt.ls-java-project
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Finished creating the Java project jdt.ls-java-project
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 Initialization failed 
Failed to import projects
org.eclipse.core.runtime.CoreException: Failed to import projects
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:136)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:107)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:244)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Failed to scan /Users/daniel
java.nio.file.AccessDeniedException: /Users/daniel/.config/htop
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2845)
	at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scanDir(BasicFileDetector.java:178)
	at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:138)
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.applies(GradleProjectImporter.java:136)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:123)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:107)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:244)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

2022/04/17 19:15:17 Unhandled message 1 java Content-Length: 166

{"jsonrpc":"2.0","method":"language/status","params":{"type":"Starting","message":"30% Starting Java Language Server - Refreshing \u0027/jdt.ls-java-project\u0027."}}
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e initialization job finished
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e build jobs finished
2022/04/17 19:15:17 Unhandled message 1 java Content-Length: 102

{"jsonrpc":"2.0","method":"language/status","params":{"type":"ServiceReady","message":"ServiceReady"}}
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e registerWatchersu0027
2022/04/17 19:15:17 2022. ápr. 17. 19:15:17 u003eu003e watchers registered

</details>

Leaving line 292 as original, running as sudo (does not throw error)
<details>
2022/04/17 19:20:52 Micro started
2022/04/17 19:20:52 ONBUFFEROPEN unknown
2022/04/17 19:20:52 ONBUFFEROPEN unknown
2022/04/17 19:20:52 ONBUFFEROPEN unknown
2022/04/17 19:20:52 Starting server java
2022/04/17 19:20:52 send java sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26392, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:20:52 send java queueing initialized
2022/04/17 19:20:52 Starting server python
2022/04/17 19:20:52 send python sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26392, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:20:52 send python queueing initialized
2022/04/17 19:20:52 Starting server go
2022/04/17 19:20:52 send go sending initialize Content-Length: 535

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26392, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:20:52 send go queueing initialized
2022/04/17 19:20:52 Starting server typescript
2022/04/17 19:20:52 send typescript sending initialize Content-Length: 567

{"jsonrpc": "2.0", "id": 0, "method": "initialize", "params": {"processId": 26392, "rootUri": "file:///Users/daniel", "workspaceFolders": [{"name": "root", "uri": "file:///Users/daniel"}], "initializationOptions": {"importMap": "./import_map.json"}, "capabilities": {"textDocument": {"hover": {"contentFormat": ["plaintext", "markdown"]}, "publishDiagnostics": {"relatedInformation": false, "versionSupport": false, "codeDescriptionSupport": true, "dataSupport": true}, "signatureHelp": {"signatureInformation": {"documentationFormat": ["plaintext", "markdown"]}}}}}}
2022/04/17 19:20:52 send typescript queueing initialized
2022/04/17 19:20:52 ONBUFFEROPEN filemanager
2022/04/17 19:20:52 ONEXIT python 
2022/04/17 19:20:52 ONEXIT go 
2022/04/17 19:20:52 ONSTDERR Starting Deno language server...
  version: 1.20.6 (release, aarch64-apple-darwin)
  executable: /opt/homebrew/bin/deno

2022/04/17 19:20:52 ONSTDERR The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.


2022/04/17 19:20:52 ONEXIT java The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.


2022/04/17 19:20:52 ONSTDERR Setting import map from workspace settings: "./import_map.json"
  Resolved import map: "/Users/daniel/import_map.json"

2022/04/17 19:20:52 send typescript sending Content-Length: 57

{"jsonrpc": "2.0", "method": "initialized", "params": {}}
2022/04/17 19:20:52 ONSTDERR Server ready.


</details>

**Comment by AndCake** [comment]
OK this helps, thanks! From what I  see the reason why it seems to not die when you're sudoing is because your system can't find the java interpreter anymore and therefore the jdt-ls just dies quietly. But otherwise it seems as if this is actually a timing issue, since the jdt-ls sends a status event before even confirming the initialization request from the client. So that looks like it is the culprit but should (hopefully) be fixable from the LSP plugin side...

**Comment by AndCake** [comment]
@szabodanika , I create a PR that should (theoretically) resolve your issue. Can you test if this works on your end?

**Comment by szabodanika** [comment]
Thanks for the heads up, I tried the updated version and I can't get it to break anymore. It just works. I tried with a newer jdtls installation as well, all work great! 🙂
