### ISSUE TITLE
Freezes on large Markdown file, starts unrelated language servers

### ISSUE THREAD

**Issue by terokarvinen** [AndCake/micro-plugin-lsp#23]
**When LSP plugin is enabled, micro freezes on big markdown files.**

**Bypass the bug by removing Markdown from lsp.server in settings.json, details below.** 

When I have micro lsp plugin enabled, opening a large (15k+ lines) Markdown file freezes micro. To continue, I have to kill it from another terminal. Without lsp plugin, micro opens the file normally. 

Logs and process list show that unrelated language servers are loaded. 

## Steps to reproduce

0) Using micro 2.0.10 and lsp 0.5.3 on Linux (micro --version; micro --plugin list). Gopls language server in path. Default settings for 'lsp.server', defined in main.lua as "python=pylsp,go=gopls,typescript=deno lsp,javascript=deno lsp,markdown=deno lsp,json=deno lsp,jsonc=deno lsp,rust=rls,lua=lua-lsp"). Deno, the language server used by default for Markdown, is not installed.
1) Wrote a simple markdown file "foo.md" with two headings and about 20 lines of body text
2) 'micro --debug foo.md'

What I expected to happen: no language servers should be loaded. Especially, unrelated Go language server gopls should not be loaded. 

What actually happens:

This short file (foo.md) can be edited normally, unlike large MarkDown files that freeze micro. 

Logs show that gopls is loaded, and gopls also visible in process list ('ps -a|grep gpls). Process tree shows that gopls is started by micro. Logs say that many language servers are loaded (picked lines from long log):

```
2022/04/20 08:36:31 Starting server python
2022/04/20 08:36:31 Starting server go
2022/04/20 08:36:31 Starting server typescript
2022/04/20 08:36:31 Starting server javascript
2022/04/20 08:36:31 Starting server markdown
2022/04/20 08:36:31 Starting server json
2022/04/20 08:36:31 Found running lsp server for  markdown firing textDocument/didOpen...
2022/04/20 08:36:31 send markdown queueing textDocument/didOpen
2022/04/20 08:36:31 go message Loading packages...
GOPATH=[redacted]
GOSUMDB=sum.golang.org
GOROOT=[redacted]
```

Update:

## Bypassing the Bug

The bug is bypassed by disabling markdown in ~/.config/micro/settings.json

```json
"lsp.server": "python=pylsp,go=gopls,rust=rls,lua=lua-lsp",
```

After this, large Markdown files can be opened normally. 

## Default settings in main.lua

In main.lua, it seems that default value for lsp.server is defined in two different ways:

```lua
local fallback = "python=pylsp,go=gopls,typescript=deno lsp,javascript=deno lsp,markdown=deno lsp,json=deno lsp,jsonc=deno lsp,rust=rls,lua=lua-lsp"
-- ...
config.RegisterCommonOption("lsp", "server", "python=pylsp,go=gopls,typescript=deno lsp,javascript=deno lsp,rust=rls,lua=lua-lsp")
```

**Comment by AndCake** [comment]
This issue should be fixed with the refactoring required for issue #22 .

**Comment by terokarvinen** [comment]
Sounds good!

**Comment by AndCake** [comment]
The attached PR should make sure that no other language servers are initialized. Can you check if this fixed the issue for you?

**Comment by szabodanika** [comment]
Not OP, but I just checked because I also had this issue and with the changes, based on the log files only the required servers start and if there is none available, then nothing, so all is perfect for me.
