### ISSUE TITLE
Send settings to language servers

### ISSUE THREAD

**Issue by terokarvinen** [AndCake/micro-plugin-lsp#24]
**Language servers take configuration from the client. For some language servers, LSP client settings are the only comprehensive way to send settings, and default settings are unusable for some projects.** 

**Update: micro-plugin-lsp can now ignore specific messages, which can solve the situation described here. See help/lsp.md for lsp.ignoreMessages.**

For example, in Python language server linting is disabled trough configuration sent by the LSP client (below). 

Without sending settings to LSP server, LSP is not usable in projects with conventions differing from defaults. For example, in one project every indented line shows "W191 indentation contains tabs". 

https://github.com/python-lsp/python-lsp-server/issues/37

```json
{
    "language_servers": {
        "pylsp": {
            "serverSettings": {
                "pylsp.plugins.pycodestyle.enabled": false,
                "pylsp.plugins.pydocstyle.enabled": false,
                "pylsp.plugins.pyflakes.enabled": false,
                "pylsp.plugins.pylint.enabled": false,
                "pylsp.plugins.mccabe.enabled": false,
            }
        }
    }
}
```

Other closed bugs show that authors of this language server expect users to supply options trough their LSP client. 

Pylsp provides many configuration options: https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

**Comment by terokarvinen** [comment]
Testing useless error messages with full pylsp debug messages

```json
"lsp.server": "python=pylsp -vvvvv,go=gopls,rust=rls,lua=lua-lsp",
```

    micro --debug foo.py

And checking the logs

{'source': 'pycodestyle', 'range': {'start': {'line': 20, 'character': 0}, 'end': {'line': 20, 'character': 34}}, 'message': 'W191 indentation contains tabs', 'code': 'W191', 'severity': 2}, {'source': 'pycodestyle', 'range': {'start': {'line': 20, 'character': 0}, 'end': {'line': 20, 'character': 34}}, 'message': 'E101 indentation contains mixed spaces and tabs', 'code': 'E101', 'severity': 2}, 
{'source': 'pycodestyle', 'range': {'start': {'line': 21, 'character': 0}, 'end': {'line': 21, 'character': 33}}, 'message': 'W191 indentation contains tabs', 'code': 'W191', 'severity': 2}]}

I can see that plugins tell the error code with a separate message. Disabling specific codes would be very useful, as it would immediately make talkative LSP servers usable. For example here, could simply disable codes W191 and E101, which put a warning ">>" on nearly every line. 

Ignoring specific codes would be especially useful here, when it's not obvious which of the ten sub plugins are causing the warning. In this example, pycodestyle is not even mentioned in my config nor my requirements.txt, so it would not be easy to find it without debugging. 

Ignoring specific codes would also be easy, as the JSON RPC message contains the code in a separate field.

**Comment by AndCake** [comment]
Based on the example I provided for Deno, you can apply the same to send initialization options (=settings) over to the LSP server. For your example it might look like this:

```
"lsp.server": "python=pylsp={\"pylsp.plugins.pylint.enabled\": false},go=gopls,rust=rls,lua=lua-lsp
```
Since I am currently naively parsing the options, handing in a complex JSON object as a initialization option (so with multiple attributes) will probably break stuff. But this is something that can be fixed relatively quickly.

**Comment by terokarvinen** [comment]
Thanks! I tried it, and got some options sent to plugins. However, pycodestyle in pylsp seems to stick. This might be a problem with pylsp, as there seems to be other comments with other editors wishing to disable or quiet down the pylsp linters. Also, it might require some mythical combination of braces and dots.

**Comment by AndCake** [comment]
I updated the parsing mechanism so it can deal with multiple initialization option attributes. Can you check if this works better for you?
