### ISSUE TITLE
How do I parse command arguments to the LSP with this plugin.

### ISSUE THREAD

**Issue by Zekiah-A** [AndCake/micro-plugin-lsp#29]
I am currently attempting to use the typescript-language-server LSP (https://github.com/typescript-language-server/typescript-language-server) with this plugin, which requres the flags `--stdio` in order to run, however after following the guide set out on the readme of this repo I can not seem to get it to work.
The relevant line in my configuration looks like:
![image](https://user-images.githubusercontent.com/73035340/177432280-177a3d0b-50b8-40d5-b869-d0edfbabdd49.png)
and the error I receive is:
![image](https://user-images.githubusercontent.com/73035340/177432314-d884af9a-cd08-481e-8c7d-a46976e97e8a.png)

Everything par this is the default config set on install. If this is an error by me, perhaps the readme could be clarified in order to make it clearer how one should do commandline args?
Thanks.

**Comment by AndCake** [comment]
Just for reference, this is where I took the information for the typescript setup from:

https://github.com/AndCake/micro-plugin-lsp/blob/master/help/lsp.md
