### ISSUE TITLE
Plugin does not work with clangd and ccls

### ISSUE THREAD

**Issue by mrkubax10** [AndCake/micro-plugin-lsp#34]
It seems like micro-plugin-lsp doesn't work with clangd and ccls, i.e. none of lsp features can be triggered.
Here is part of my `settings.json` file with micro-plugin-lsp configuration:
```json
"lsp.server": "cpp=clangd --log=error",
"lsp.autocompleteDetails": false,
"lsp.formatOnSave": false,
"lsp.ignoreMessages": "LS message1 to ignore|LS message 2 to ignore|...",
"lsp.ignoreTriggerCharacters": "completion,signature",
"lsp.tabcompletion": true
```

**Comment by mrkubax10** [comment]
Not sure if I understood correctly but you can use this C++ example:
```cpp
#include <iostream>

class Test{
public:
    void test(){
        std::cout<<"Test"<<std::endl;
    }
};

int main(){
    Test test;
    test. // After pressing Ctrl+Space here completion event should be triggered but nothing happens
    return 0;
}
```

**Comment by AndCake** [comment]
It seems the correct filetype to go into the lsp.server configuration is not "cpp" but "c++". So the correct configuration string would look like this:

```
"lsp.server": "c++=clangd"
```

or for ccls:
```
"lsp.server": "c++=ccls"
```

However, the `+` characters in the filetype are unexpected and lead to an issue parsing this directive. I will investigate this further.

**Comment by AndCake** [comment]
@mrkubax10 : I created a fix for the above issue in the attached PR. Can you check if this fixes the issue on your side?

**Comment by mrkubax10** [comment]
Yes, this fixes the issue
