### ISSUE TITLE
Ctrol-Cpace does not work on Macos

### ISSUE THREAD

**Issue by bashery** [AndCake/micro-plugin-lsp#37]
Hello!

Ctrol-Cpace does not work for completion on Macos Iterm2,

Note:
I set ```Preferences->Profiles->Keys->Presets``` and  ```Esc+```  

Thanks.

**Comment by AndCake** [comment]
Since I actually don't have access to a Mac at the moment, I am currently unable to test / confirm this bug. Can anyone check and provide more details on this?
