### ISSUE TITLE
lsp.server setting gets remove from .config/micro/settings.json

### ISSUE THREAD

**Issue by neurocyte** [AndCake/micro-plugin-lsp#4]
When I exit micro it re-writes the setting.json file and removes the lsp.server value.

I am running micro master and micro-plugin-lsp master.

Removing all other plugins did not help.

**Comment by AndCake** [comment]
Thanks for the feedback. I also have the issue from time to time and I am not quite sure how to fix it at this point. It appears to be related to https://github.com/zyedidia/micro/issues/2132

**Comment by AndCake** [comment]
I created a PR that should circumvent the issue by defining it outside the settings.json (in an environment variable). Can you check if this works for you? It's in the 4-settings-fallback branch.

**Comment by neurocyte** [comment]
Yes, the MICRO_LSP environment variable works well form me. It also is a workaround for another issue I have where micro-plugin-lsp loads all configured language servers, irrespective of file type.

**Comment by phil294** [comment]
only `"lsp.server"` seems to be overwritten though - other invalid keys (for example, I made backups called `"lllllsp.server"` and such) never get deleted.

**Comment by AndCake** [comment]
@phil294 - can you check if the issue persists for you with the changes in the branch bugfix/4-settings-lost ?

Thanks!

**Comment by phil294** [comment]
jip, works now!
