### ISSUE TITLE
How To Ignore THIS ERRORS?????????????

### ISSUE THREAD

**Issue by s3rgeym** [AndCake/micro-plugin-lsp#41]
![image](https://user-images.githubusercontent.com/12753171/188934322-9a037547-3101-4af7-94a8-90bf527e4a7c.png)

It's DOES NOT WORK

![image](https://user-images.githubusercontent.com/12753171/188935360-44369a77-5662-43ff-a08f-b59a58cf2121.png)

**Comment by s3rgeym** [comment]
I modify LUA code and seen:

![image](https://user-images.githubusercontent.com/12753171/188948574-abbac37b-150e-410c-9119-3d2ad5ffdb67.png)

But in micro i see this shit

![image](https://user-images.githubusercontent.com/12753171/188948703-7345787a-ff5b-4c7e-8e99-d29bc885eae8.png)
 
C0116 !=

**Comment by sebkolind** [comment]
@s3rgeym Do you honestly believe that anyone would help you when you've got that attitude?
