### ISSUE TITLE
Doesn't initialize when opening file from filemanager

### ISSUE THREAD

**Issue by kra-mo** [AndCake/micro-plugin-lsp#45]
The server does not start if the file is opened via the [filemanager](https://github.com/NicolaiSoeborg/filemanager-plugin) plugin. I'm not sure which plugin causes this issue, so I'm filing it here for now.

**Comment by AndCake** [comment]
Hi @kra-mo - thanks for reporting this. I will take a look into this to see how this happens.

**Comment by AndCake** [comment]
I implemented a fix for the issue. Can you check it out and see if this fixed it for you too? 

Thanks!

**Comment by kra-mo** [comment]
It did! Thank you! :)
