### ISSUE TITLE
How to set up julia language server

### ISSUE THREAD

**Issue by KronosTheLate** [AndCake/micro-plugin-lsp#50]
I am trying to set up the LSP for Julia, after having just done it successfully for Helix.

The relevant variable in ~/.config/helix.config.toml is 
```
language-server = { command = "julia", args = [
    "--project=@helix-lsp",
    "--startup-file=no",
    "--history-file=no",
    "-e",
    "using LanguageServer; runserver()"
    ] }
```

So the language server is started by running the following command from the shell:
`julia --project=@helix-lsp --startup-file=no --history-file=no -e "using LanguageServer; runserver()"`

I take it that what I need to do is to define that command in ~/.config/micro/settings.json, as in the following pseudocode:
`"lsp.server": "python=pyls, rust=rls, julia=my_command",`

My initial issue is that my command uses `"` symbols. Can those simply be escaped, as in the following attempt?
`"lsp.server": "python=pyls, rust=rls, julia=julia --project=@helix-lsp --startup-file=no --history-file=no -e \"using LanguageServer; runserver()\"",`
Because I see no effect from this.

Or would I _have_ to define a shell script that launches the language server? Could you provide an example of what that file should look like, and where it should be saved?

**Comment by AndCake** [comment]
I was able to get Julia's language server started using this technique on the latest master:

```
{
   "lsp.server": "julia=julia --project%3d@helix-lsp --startup-file%3dno --history-file%3dno -e using%20LanguageServer;%20runserver()"
}
```

Please note that absence of quotes behind the `-e` and also I applied URI encoding to the parameters to avoid parsing errors.

After that, I noticed, however, that the Julia language server required some more attention. First of all, the languageServer package needed to be installed using `import Pkg; Pkg.add("LanguageServer")` (which I did on the Julia Repl). Once that complete, it took quite a while to download and cache all dependencies but eventually it did give me proper diagnostics and formatting seemed to work fine too. 

Can you check if this works for you too?

**Comment by KronosTheLate** [comment]
Cool, my first assignment! Thanks for your effort.

With the following `.config/micro/settings.json` filte:
```
{
    "lsp.server": "julia=julia --startup-file%3dno --history-file%3dno -e using%20LanguageServer;%20runserver()"
}
```
I am _not_ getting LSP features (testing with "Alt+k" and "Alt+d").

To simplify things, I removed the `--project` argument. It was not being used anyways for Helix. Instead, I have LanguageServer.jl installed in my global enviroment, which should be one less thing that could be wrong.
I also have this extension installed for micro.

**Comment by AndCake** [comment]
Can you try to use the latest master for this instead of the currently released version? The latest master has support for the URL encoding for commands in the settings. This might fix the issue...

**Comment by KronosTheLate** [comment]
Yes, that works! Awesome. I am getting a little confused about the results sometimes, but I think that is all about my Julia environments. The LSP server works!

Currently, when I do alt+k over a function, the docstring is shown in the bottom panel, which looks quite bad:
<img width="960" alt="image" src="https://github.com/AndCake/micro-plugin-lsp/assets/61620837/4c2af9a3-625e-4ad4-8a68-33504cd7a334">

Would it be possible to bring up a pager for alt+k?

Also, doing alt+d on any library function takes me to an empty file. However, doing it on on a function defined in the same file works like a charm.

**Comment by AndCake** [comment]
I think a pager for alt+k might be a little disruptive to some since it would start a new process in the foreground and therefore hide the editor until the pager is closed again. But maybe just showing the documentation in a little bufpane would help. At least new lines and such would be properly displayed.

**Comment by AndCake** [comment]
I added the closable bufpane for when you also have `lsp.autocompleteDetails` enabled. This bufpane will now only show up if that option is set to true and if the message shown for the hover is at least 2 lines.

**Comment by KronosTheLate** [comment]
That sounds great. Thank you.
