### ISSUE TITLE
PHP support is working

### ISSUE THREAD

**Issue by keyle** [AndCake/micro-plugin-lsp#51]
Thanks for this excellent plugin. Life changer.

I'd like to point out that adding support for PHP with intelephense (the standard LSP for PHP) was really easy. 

All it needs is to be declared and use `--stdio` parameter.

e.g. my settings:

`"lsp.server": "c=clangd,php=intelephense --stdio,python=...`

and of course intelephense needs to be installed. You might want to add it as a documentation that PHP can be supported!

HTH.

**Comment by AndCake** [comment]
Great thanks for the feedback! I'm glad PHP can be supported too. I will add it to the existing documentation.

**Comment by AndCake** [comment]
I updated master to include the corresponding documentation.
