### ISSUE TITLE
format on save should be false by default

### ISSUE THREAD

**Issue by X-Ryl669** [AndCake/micro-plugin-lsp#52]
This is really disturbing that a language server plugin changes the file while saving. 

It shouldn't do that by default at least, since it might go unnoticed (like when auto saving on quit). 
This breaks many repository that have different coding convention since formatting is per project dependent.

**Comment by AndCake** [comment]
This has been implemented now (release v0.6.3).

**Comment by X-Ryl669** [comment]
Thanks!

**Comment by zoomosis** [comment]
This format-on-save bug bit me after I ran:

``micro -plugin install lsp``

since the current release of lsp is still 0.6.2.

I was working on a Markdown file at the time, where it completely obliterated the formatting. Fortunately I had a backup...
