### ISSUE TITLE
Using zk lsp, go to definition fails if there are spaces in filename

### ISSUE THREAD

**Issue by quesada** [AndCake/micro-plugin-lsp#56]
This might be a lost case, but...

When using 'alt-d' on a wikilink in a markdown file, after setting 'zk lsp' as the LSP in the config, it works beautifully for one-word jumps, but fails if there are spaces in the filename. Example:

It works:
[[tpnote]] (this is an existing file, it opens it)

It fails:
[[Just use unix]] (this is an existing file, it opens a blank file instead)
![image](https://github.com/AndCake/micro-plugin-lsp/assets/182207/ecdcd2e4-7019-47c3-a226-f5d937f2f3cc)

Is there any way to fix this? (other than sluggifying all filenames).

Thanks!

**Comment by AndCake** [comment]
Ah yes it seems the URL encoding is not yet decoded. Will take a look when I get some time for it. Should be a relatively easy fix.

**Comment by AndCake** [comment]
This should be fixed now with release v0.6.3
