### ISSUE TITLE
Key Bindings not working on Mac

### ISSUE THREAD

**Issue by Tucker-Adkison** [AndCake/micro-plugin-lsp#58]
#### Description
Key bindings are not working on mac. I tried the keybindins with gopls and deno lsp. 

I see there is a branch dedicated to the key binding issue on mac, but there seems to be no progress for a while now.

#### To Reproduce
* Install this plugin on Mac
* Install gopls
* Open a go file and test the keybindings

**Comment by AndCake** [comment]
Did you check the proposed solution in #47 ? This ticket appears to be a duplicate of it…

**Comment by tucker-adkison** [comment]
It ended up working with the newest commits. Not sure what caused the issue for me.
