### ISSUE TITLE
Feature request: Find references

### ISSUE THREAD

**Issue by terokarvinen** [AndCake/micro-plugin-lsp#6]
Thank you for LSP support, AndCake!

"Find references" would be useful addition for navigating code. 

## What it does

User puts cursor over "myFunction(foo, bar=123)" and presses alt-S. A list of all calls to myFunction() are listed. User chooses one of the uses. The file opens in a new tab, on the row making a call to myFunction(). 

## User interface

The plugin already supports "hover"/"show function signature" (alt-K) and "jump to definition" (alt-D). The reverse option, finding all uses of function, variable or class under cursors would help navigating code. 

The UI of alt-K and alt-D is very obvious and successful. Both of them have a single result, so pressing the key can immediately perform the action. But usually, there are many references, and user must choose which of those he wants to jump to. 

The choice could be presented with fzf fuzzy search, micro "command bar" style or a drop down menu.

For fzf fuzzy search, the approach could be similar to my [micro jump plugin](https://github.com/terokarvinen/micro-jump/blob/main/jump.lua). The upsides are that it's pleasant to use. The downside is that it requires fzf installed, which requires extra steps on systems lacking package managers, like Windows. Fzf is written in Go, so maybe it could be included in micro some day. Any plugin requiring user to choose something could benefit from this, and there are already multiple plugins using fzf. 

For micro command bar implementation, there is already tab completion and possibility to show different options while user is typing. I don't know if this interface is conveniently available to plugins. As the space for showing different options is limited to a single line, this might not be an ideal UI. 

[Drop down menu has been tested](https://github.com/zyedidia/micro/pull/977#issuecomment-366428410) in completion support that never made it to micro. I don't know if micro supports drop downs or not. Depending on how it's done, there might be more space to show all the references. Drop down menus should not jump on your face automatically. 

The feature could have a mnemonic name related to the shortcut, for example Alt-S -> Search references, alt-L List refereces. 

## Backend implementation

I wonder if this is "find references" in LSP:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references

**Comment by AndCake** [comment]
@terokarvinen I added some functionality for doing the references lookup. Can you checkout the branch feature/6-find-references and see if you find it usable? Thanks!

**Comment by terokarvinen** [comment]
Thanks, @AndCake! I'll try it out.

**Comment by terokarvinen** [comment]
@AndCake, I tested feature/6-find-references with Go and gopls. It worked!

You succeeded with the UI, again. It's obvious and intuitive. Half window is pretty much the right size: It has enough space to show all the data, but still shows enough code to help keep context. Better than some of my suggestions above, it's completely based on facilities provided by micro today. 

This is a very good solution to the feature request. 

An idea for future development, depending on whether language servers give this information: could the references lookup window give context information, such as the function or line where the reference is? E.g. "foo.go:42:73 # bar()". The current PR already solves the bug, and does it well, so this is just a bonus idea. 

Thanks!

**Comment by AndCake** [comment]
Hey @terokarvinen - thanks for testing the feature! For the additional information in the references lookup, I saw that the context information you described is sadly not provided by the LSPs. I was thinking to eventually include a little preview of the line (or surrounding three lines) in which the reference occurs for each entry. This will make the result overview look a little more cluttered, though (and syntax highlighting would be missing), so I left it out for the moment. 

Maybe something for a later point in time.

**Comment by terokarvinen** [comment]
Thanks @AndCake! 

Showing the context some day in the future is useful also without syntax highlight. I've noticed that I use my own jump plugin as table of contents. That means that, especially for long Markdown texts, I look at it not just to jump but also to get an overview. The context in references could provide similar overview of function usage, even before / without jump. 

This is great addition to LSP plugin, I'm already using it. Happy to see it land on the public version.
